In [1]:
import pandas as pd

In [ ]:
bus=pd.read_csv('../data/SG/bus_with_grid_id_new.csv')
bus

,station,arrive_time,lat,lon,trajectory_id,geometry,loc_index,loc_id
0,Bedok Reservoir Rd - the Clearwater Condo (75349),06:01,1.338059,103.933909,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.93390854120808 1.338059232571393),555,<LOC_555>
1,Bedok Reservoir Rd - Waterfront Key (84609),06:02,1.337908,103.931288,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.93128837984756 1.3379082644823823),555,<LOC_555>
2,Bedok Reservoir Rd - Aft Waterfront Waves (84639),06:03,1.338591,103.929361,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.9293609201018 1.3385913334645825),555,<LOC_555>
3,Bedok Reservoir Rd - Waterfront Isle (84619),06:04,1.338962,103.927414,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.9274144508834 1.3389623484635167),555,<LOC_555>
4,Bedok Reservoir Rd - Blk 716 (84629),06:05,1.338178,103.925416,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.92541602007374 1.3381775622352343),555,<LOC_555>
...,...,...,...,...,...,...,...,...
1221624,Toa Payoh East - Blk 25 (52319),01:00,1.334123,103.857038,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.8570383498762 1.334123168553112),59,<LOC_59>
1221625,Lor 6 Toa Payoh - Blk 27 (52331),01:00,1.332507,103.855829,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.85582893567332 1.3325070209474847),60,<LOC_60>
1221626,Lor 6 Toa Payoh - Aft Safra Toa Payoh (52321),01:02,1.331240,103.852627,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.85262693019864 1.3312399078793593),34,<LOC_34>
1221627,Lor 6 Toa Payoh - Toa Payoh Swim Cplx (52501),01:03,1.330921,103.850061,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.85006122407994 1.3309210812633612),34,<LOC_34>
1221628,Lor 6 Toa Payoh - Toa Payoh Int (52009),00:45,1.332797,103.847567,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.84756742104037 1.3327965085159326),33,<LOC_33>

In [ ]:
bus = bus[bus['arrive_time'] != "-"]
bus

,station,arrive_time,lat,lon,trajectory_id,geometry,loc_index,loc_id
0,Bedok Reservoir Rd - the Clearwater Condo (75349),06:01,1.338059,103.933909,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.93390854120808 1.338059232571393),555,<LOC_555>
1,Bedok Reservoir Rd - Waterfront Key (84609),06:02,1.337908,103.931288,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.93128837984756 1.3379082644823823),555,<LOC_555>
2,Bedok Reservoir Rd - Aft Waterfront Waves (84639),06:03,1.338591,103.929361,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.9293609201018 1.3385913334645825),555,<LOC_555>
3,Bedok Reservoir Rd - Waterfront Isle (84619),06:04,1.338962,103.927414,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.9274144508834 1.3389623484635167),555,<LOC_555>
4,Bedok Reservoir Rd - Blk 716 (84629),06:05,1.338178,103.925416,59 - Bishan Int Schedule.csv_Departure #1,POINT (103.92541602007374 1.3381775622352343),555,<LOC_555>
...,...,...,...,...,...,...,...,...
1221624,Toa Payoh East - Blk 25 (52319),01:00,1.334123,103.857038,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.8570383498762 1.334123168553112),59,<LOC_59>
1221625,Lor 6 Toa Payoh - Blk 27 (52331),01:00,1.332507,103.855829,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.85582893567332 1.3325070209474847),60,<LOC_60>
1221626,Lor 6 Toa Payoh - Aft Safra Toa Payoh (52321),01:02,1.331240,103.852627,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.85262693019864 1.3312399078793593),34,<LOC_34>
1221627,Lor 6 Toa Payoh - Toa Payoh Swim Cplx (52501),01:03,1.330921,103.850061,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.85006122407994 1.3309210812633612),34,<LOC_34>
1221628,Lor 6 Toa Payoh - Toa Payoh Int (52009),00:45,1.332797,103.847567,238 - Toa Payoh Int Schedule.csv_Departure #255,POINT (103.84756742104037 1.3327965085159326),33,<LOC_33>

In [ ]:
bus['min_of_day'] = pd.to_datetime(bus['arrive_time'], format='%H:%M').dt.hour * 60 + pd.to_datetime(bus['arrive_time'], format='%H:%M').dt.minute
bus = bus.sort_values(by=['trajectory_id', 'arrive_time']).reset_index(drop=True)
bus

/tmp/ipykernel_396070/688094464.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bus_wuxi['min_of_day'] = pd.to_datetime(bus_wuxi['arrive_time'], format='%H:%M').dt.hour * 60 + pd.to_datetime(bus_wuxi['arrive_time'], format='%H:%M').dt.minute

,station,arrive_time,lat,lon,trajectory_id,geometry,loc_index,loc_id,min_of_day
0,Upp Changi Rd - Aft Sungei Bedok (85089),05:09,1.333321,103.948692,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.94869187789904 1.333321405759147),759,<LOC_759>,309
1,Bedok Rd - Bedok Mkt Pl (85069),05:10,1.331685,103.947462,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.94746166801366 1.3316846337803432),760,<LOC_760>,310
2,Bedok Rd - Bef Jln Chempaka Kuning (85059),05:11,1.329425,103.949135,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.94913479068305 1.3294247852317715),760,<LOC_760>,311
3,Bedok Rd - Opp Man Fatt Lam Tp (85049),05:12,1.326651,103.951302,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.95130222754862 1.326650611890011),760,<LOC_760>,312
4,Bedok Rd - Opp Excelsior Gdns (85039),05:14,1.324365,103.953030,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.95303047564109 1.3243654617352052),874,<LOC_874>,314
...,...,...,...,...,...,...,...,...,...
1176362,New Upp Changi Rd - the Tanamera Condo (84061),18:35,1.325884,103.942280,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94228036133325 1.325884466622376),654,<LOC_654>,1115
1176363,New Upp Changi Rd - Tanah Merah Stn Exit B (85...,18:37,1.327578,103.946516,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94651587541172 1.3275783450590195),760,<LOC_760>,1117
1176364,Bedok Rd - Aft Jln Chempaka Kuning (85051),18:39,1.329509,103.948837,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94883708396922 1.3295085486798095),760,<LOC_760>,1119
1176365,Bedok Rd - Opp Bedok Mkt Pl (85061),18:40,1.331561,103.947313,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94731282487687 1.3315613932476078),760,<LOC_760>,1120
1176366,Upp Changi Rd - Bef Jln Pari Burong (85081),18:41,1.332963,103.947264,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94726404924026 1.332963265429018),759,<LOC_759>,1121

In [ ]:
bus['prev_id'] = bus['trajectory_id'].shift(1)
bus['prev_min'] = bus['min_of_day'].shift(1)
bus['diff'] = bus['min_of_day'] - bus['prev_min']

# 找出“脏ID”：同一个ID内部，出现了 > 60 分钟间隔
# 这里的逻辑是：只要这条轨迹里有哪怕一次瞬移，整条轨迹我都不要了，以防万一
dirty_mask = (bus['trajectory_id'] == bus['prev_id']) & (bus['diff'] > 30)
dirty_ids = bus.loc[dirty_mask, 'trajectory_id'].unique()

print(f"发现脏轨迹(含大断层)数量: {len(dirty_ids)}")

发现脏轨迹(含大断层)数量: 1794

In [6]:
dirty_ids

array(['10 - Kent Ridge Ter Schedule.csv_Departure #103',
       '10 - Kent Ridge Ter Schedule.csv_Departure #104',
       '10 - Kent Ridge Ter Schedule.csv_Departure #105', ...,
       '992 - Bt Batok Int Schedule.csv_Departure #171',
       '992 - Tengah int Schedule.csv_Departure #162',
       '993 - Jurong East Int Schedule.csv_Departure #60'], dtype=object)

In [ ]:
bus[bus['trajectory_id'] =='10 - Kent Ridge Ter Schedule.csv_Departure #103']

,station,arrive_time,lat,lon,trajectory_id,geometry,loc_index,loc_id,min_of_day,prev_id,prev_min,diff
340,Pasir Panjang Rd - Aft Sth Buona Vista Rd (15...,00:00,1.279545,103.785473,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.78547252233476 1.2795448057112395),261,<LOC_261>,0,10 - Kent Ridge Ter Schedule.csv_Departure #102,1437.0,-1437.0
341,Pasir Panjang Rd - Barossa Gdns (16201),00:01,1.281279,103.784152,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.78415240829491 1.2812785551572612),261,<LOC_261>,1,10 - Kent Ridge Ter Schedule.csv_Departure #103,0.0,1.0
342,Pasir Panjang Rd - Opp Haw Par Villa Stn (16011),00:02,1.282840,103.781789,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.78178887594012 1.2828401859284686),261,<LOC_261>,2,10 - Kent Ridge Ter Schedule.csv_Departure #103,1.0,1.0
343,Pasir Panjang Rd - Opp Gloria Mansion (16021),00:04,1.286247,103.779922,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.77992193578729 1.2862474908441777),262,<LOC_262>,4,10 - Kent Ridge Ter Schedule.csv_Departure #103,2.0,2.0
344,Pasir Panjang Rd - Opp S'Pore Science Pk II (1...,00:05,1.288058,103.778477,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.77847708557982 1.2880578719802576),202,<LOC_202>,5,10 - Kent Ridge Ter Schedule.csv_Departure #103,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
403,Pasir Panjang Rd - Labrador Pk Stn (15141),23:54,1.272807,103.800859,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.80085878756654 1.2728071141796726),327,<LOC_327>,1434,10 - Kent Ridge Ter Schedule.csv_Departure #103,1432.0,2.0
404,Pasir Panjang Rd - Opp Mapletree Biz City (15151),23:55,1.273945,103.798081,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.79808109566191 1.273944646330821),328,<LOC_328>,1435,10 - Kent Ridge Ter Schedule.csv_Departure #103,1434.0,1.0
405,Pasir Panjang Rd - Opp Harbourside Bldg 2 (15161),23:56,1.274478,103.796623,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.7966230539738 1.274477842945004),328,<LOC_328>,1436,10 - Kent Ridge Ter Schedule.csv_Departure #103,1435.0,1.0
406,Pasir Panjang Rd - Pasir Panjang Stn/Fc (15191),23:57,1.275938,103.792431,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.79243121012196 1.27593828323674),328,<LOC_328>,1437,10 - Kent Ridge Ter Schedule.csv_Departure #103,1436.0,1.0
407,Pasir Panjang Rd - Aft Pasir Panjang Stn (15201),23:59,1.276868,103.789593,10 - Kent Ridge Ter Schedule.csv_Departure #103,POINT (103.7895925033649 1.2768680570068165),329,<LOC_329>,1439,10 - Kent Ridge Ter Schedule.csv_Departure #103,1437.0,2.0

In [ ]:
bus = bus[~bus['trajectory_id'].isin(dirty_ids)].copy()
bus

,station,arrive_time,lat,lon,trajectory_id,geometry,loc_index,loc_id,min_of_day,prev_id,prev_min,diff
0,Upp Changi Rd - Aft Sungei Bedok (85089),05:09,1.333321,103.948692,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.94869187789904 1.333321405759147),759,<LOC_759>,309,None,NaN,NaN
1,Bedok Rd - Bedok Mkt Pl (85069),05:10,1.331685,103.947462,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.94746166801366 1.3316846337803432),760,<LOC_760>,310,10 - Kent Ridge Ter Schedule.csv_Departure #1,309.0,1.0
2,Bedok Rd - Bef Jln Chempaka Kuning (85059),05:11,1.329425,103.949135,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.94913479068305 1.3294247852317715),760,<LOC_760>,311,10 - Kent Ridge Ter Schedule.csv_Departure #1,310.0,1.0
3,Bedok Rd - Opp Man Fatt Lam Tp (85049),05:12,1.326651,103.951302,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.95130222754862 1.326650611890011),760,<LOC_760>,312,10 - Kent Ridge Ter Schedule.csv_Departure #1,311.0,1.0
4,Bedok Rd - Opp Excelsior Gdns (85039),05:14,1.324365,103.953030,10 - Kent Ridge Ter Schedule.csv_Departure #1,POINT (103.95303047564109 1.3243654617352052),874,<LOC_874>,314,10 - Kent Ridge Ter Schedule.csv_Departure #1,312.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1176362,New Upp Changi Rd - the Tanamera Condo (84061),18:35,1.325884,103.942280,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94228036133325 1.325884466622376),654,<LOC_654>,1115,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1113.0,2.0
1176363,New Upp Changi Rd - Tanah Merah Stn Exit B (85...,18:37,1.327578,103.946516,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94651587541172 1.3275783450590195),760,<LOC_760>,1117,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1115.0,2.0
1176364,Bedok Rd - Aft Jln Chempaka Kuning (85051),18:39,1.329509,103.948837,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94883708396922 1.3295085486798095),760,<LOC_760>,1119,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1117.0,2.0
1176365,Bedok Rd - Opp Bedok Mkt Pl (85061),18:40,1.331561,103.947313,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94731282487687 1.3315613932476078),760,<LOC_760>,1120,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1119.0,1.0
1176366,Upp Changi Rd - Bef Jln Pari Burong (85081),18:41,1.332963,103.947264,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94726404924026 1.332963265429018),759,<LOC_759>,1121,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1120.0,1.0

In [ ]:
bus['trajectory_id'].value_counts().describe()

count    33757.000000
mean        32.808514
std         20.380330
min          1.000000
25%         16.000000
50%         30.000000
75%         47.000000
max        101.000000
Name: count, dtype: float64

In [ ]:
import numpy as np
def split_long_trajectories(df, threshold=60):
    """
    对长度超过 threshold 的轨迹进行中点切分。
    """
    # 1. 首先确保轨迹内是有序的（按时间排序）
    df = df.sort_values(['trajectory_id', 'arrive_time'])
    
    # 2. 计算每个轨迹的长度
    traj_lengths = df.groupby('trajectory_id').size()
    
    # 3. 区分需要切分和不需要切分的 ID
    long_traj_ids = traj_lengths[traj_lengths > threshold].index
    print(f"共有 {len(long_traj_ids)} 条轨迹长度超过 {threshold}，即将进行切分。")

    # 4. 定义切分函数（用于 apply）
    def process_group(group):
        n = len(group)
        if n > threshold:
            mid = n // 2
            # 第一部分
            part1 = group.iloc[:mid].copy()
            part1['trajectory_id'] = part1['trajectory_id'].astype(str) + '_part1'
            # 第二部分
            part2 = group.iloc[mid:].copy()
            part2['trajectory_id'] = part2['trajectory_id'].astype(str) + '_part2'
            return pd.concat([part1, part2])
        else:
            return group

        # 5. 执行切分操作
    # 使用 groupby().apply() 能够保留所有原始列
    df_processed = df.groupby('trajectory_id', group_keys=False).apply(process_group)
    '''
    apply 执行完毕后，Pandas 会收集所有函数返回的 DataFrame，并将它们纵向堆叠（Stack）起来
    '''
    
    return df_processed

bus_new = split_long_trajectories(bus, threshold=60)
bus_new

共有 3218 条轨迹长度超过 60，即将进行切分。

/tmp/ipykernel_396070/2545678784.py:33: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_processed = df.groupby('trajectory_id', group_keys=False).apply(process_group)

,station,arrive_time,lat,lon,trajectory_id,geometry,loc_index,loc_id,min_of_day,prev_id,prev_min,diff
0,Upp Changi Rd - Aft Sungei Bedok (85089),05:09,1.333321,103.948692,10 - Kent Ridge Ter Schedule.csv_Departure #1_...,POINT (103.94869187789904 1.333321405759147),759,<LOC_759>,309,None,NaN,NaN
1,Bedok Rd - Bedok Mkt Pl (85069),05:10,1.331685,103.947462,10 - Kent Ridge Ter Schedule.csv_Departure #1_...,POINT (103.94746166801366 1.3316846337803432),760,<LOC_760>,310,10 - Kent Ridge Ter Schedule.csv_Departure #1,309.0,1.0
2,Bedok Rd - Bef Jln Chempaka Kuning (85059),05:11,1.329425,103.949135,10 - Kent Ridge Ter Schedule.csv_Departure #1_...,POINT (103.94913479068305 1.3294247852317715),760,<LOC_760>,311,10 - Kent Ridge Ter Schedule.csv_Departure #1,310.0,1.0
3,Bedok Rd - Opp Man Fatt Lam Tp (85049),05:12,1.326651,103.951302,10 - Kent Ridge Ter Schedule.csv_Departure #1_...,POINT (103.95130222754862 1.326650611890011),760,<LOC_760>,312,10 - Kent Ridge Ter Schedule.csv_Departure #1,311.0,1.0
4,Bedok Rd - Opp Excelsior Gdns (85039),05:14,1.324365,103.953030,10 - Kent Ridge Ter Schedule.csv_Departure #1_...,POINT (103.95303047564109 1.3243654617352052),874,<LOC_874>,314,10 - Kent Ridge Ter Schedule.csv_Departure #1,312.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1176362,New Upp Changi Rd - the Tanamera Condo (84061),18:35,1.325884,103.942280,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94228036133325 1.325884466622376),654,<LOC_654>,1115,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1113.0,2.0
1176363,New Upp Changi Rd - Tanah Merah Stn Exit B (85...,18:37,1.327578,103.946516,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94651587541172 1.3275783450590195),760,<LOC_760>,1117,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1115.0,2.0
1176364,Bedok Rd - Aft Jln Chempaka Kuning (85051),18:39,1.329509,103.948837,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94883708396922 1.3295085486798095),760,<LOC_760>,1119,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1117.0,2.0
1176365,Bedok Rd - Opp Bedok Mkt Pl (85061),18:40,1.331561,103.947313,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94731282487687 1.3315613932476078),760,<LOC_760>,1120,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1119.0,1.0
1176366,Upp Changi Rd - Bef Jln Pari Burong (85081),18:41,1.332963,103.947264,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,POINT (103.94726404924026 1.332963265429018),759,<LOC_759>,1121,9A - Loyang Ave (Blk 149a) Schedule.csv_Depart...,1120.0,1.0

In [ ]:
bus_new['trajectory_id'].value_counts().describe()

count    36975.000000
mean        29.953130
std         15.041911
min          1.000000
25%         17.000000
50%         31.000000
75%         41.000000
max         60.000000
Name: count, dtype: float64

In [ ]:
bus_new.to_csv('../data/SG/ultimate_bus_traj_new.csv',index=False)